### PR TITLE
Providing option to select specific nifty index stocks.

### LINKED ISSUE #59: Providing option to select specific nifty index stocks.
Currently, we are screening all NSE stocks. we can provide an option to select specific nifty index stocks.

image

As shown in the above image.

Can I make PR ?

### PR DESCRIPTION
**Pull request by swarpatel23**

### CODE REVIEW

**Comment by pranjal-joshi** [comment]
@swarpatel23 
The earlier method of [using a counter](https://github.com/pranjal-joshi/Screeni-py/blob/4d7d7f604830d645629cb849921c1e12689ef0d8/src/classes/Utility.py#L102) for `cache update` doesn't work with this index-wise screening.

Steps to reproduce the bug:
1. Run nifty 200 screening in after market hours.
2. Now these 200 stocks will be cached.
3. Then run nifty midcap 100.
4. These 100 stocks are not in cache, but as `cache size (200) > fetched data size (100)` the newly screened stocks are not getting saved in the cache.

We need some elegant solution for this. Maybe actually search whether the symbol is in the cache dictionary and add it if not exist?

**Comment by swarpatel23** [comment]
Ok, got the point. working on it...

**Comment by pranjal-joshi** [comment]
Tested 88adc4e.
It works as expected only if the program is not exited.

But If the program cached say Nifty 50, Midcap 50 and then you start screening Smallcap 50, It will tell you that data has been already cached at the end of screening. What we want is to append this newly downloaded data to the pickle.

**Comment by swarpatel23** [comment]
Agree, Currently, if we have more data in stockdict then previous pickle then it will override the existing pickle and it's efficient. If we try to update already existing pickle then we have to go through five steps reading, deserialization, updating, serialization and writing. While in case of overriding we only go through serialization and writing.

**Comment by pranjal-joshi** [comment]
Fixed in 5225a37
Where the `saveStockData` method checks if each and every symbol in `listStockCodes` is available in `stockDict` as a key.
If it is there, then it will overwrite the pickle.
Test and let me know.

**Pull request merged**
