### PR TITLE
added makefile

### PR DESCRIPTION
**Pull request by soodrohit**
added makefile for docker actions

### CODE REVIEW

**Comment by pranjal-joshi** [comment]
Hi @soodrohit 

Can you explain how the makefile is getting used and what's the exact purpose?

**Comment by soodrohit** [comment]
Hi Pranjal,

The makefile is a automation tool for build management, since you have
dockerized your project, so this is a faster way of getting the docker
running, as an alternative of doing the same on Docker Dashboard as per
your setup video.

One can simply run the make commands to achieve the same. E.g.

if you run the following command on your directory,

> make run
this will start the docker container with the specified port in the
background, so that your command line is not blocked

> make rebuild
this will be useful, as one goes about making code changes and would like
to build and start again..

Hope this helps..
~Rohit

**Comment by pranjal-joshi** [comment]
Hi @soodrohit 

Is it possible for you to move this PR to `new-features` branch?
The new feature test and CI-CD is attached to that branch!
Consider opening a new PR on that branch if it can't be moved

**Comment by soodrohit** [comment]
> Hi @soodrohit
> 
> Is it possible for you to move this PR to `new-features` branch? The new feature test and CI-CD is attached to that branch! Consider opening a new PR on that branch if it can't be moved

@pranjal-joshi sure.. will move it there

**Pull request closed without merging**
